#!/usr/bin/env bash
# ============================================================
#  Rocko_DE_Final — Deploy Script
#  CachyOS + Hyprland + Noctalia stack
#
#  Usage:
#    git clone https://github.com/ohnoibrokeit/Rocko_DE_Final.git
#    cd Rocko_DE_Final && bash deploy.sh
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"
CONFIG="$HOME/.config"

# ── Colors ───────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}→${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }
warn()    { echo -e "${YELLOW}⚠${NC} $1"; }
error()   { echo -e "${RED}✗${NC} $1"; exit 1; }

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Rocko_DE_Final — Deploy Script       ║${NC}"
echo -e "${BLUE}║     CachyOS + Hyprland + Noctalia        ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Sanity check ─────────────────────────────────────────
if ! command -v paru &>/dev/null; then
    error "paru not found. Install paru first: https://github.com/Morganamilo/paru"
fi

# ── 1. Packages ──────────────────────────────────────────
info "Installing packages..."

PACKAGES=(
    # Compositor
    hyprland
    hypridle
    hyprpolkitagent
    pyprland

    # Shell
    noctalia-qs
    noctalia-shell

    # Terminal & fetch
    kitty
    fastfetch
    fish

    # Clipboard
    cliphist
    wl-clipboard
    wl-clip-persist

    # Screenshots
    grim
    slurp
    satty

    # Theming
    adw-gtk-theme
    qt6ct
    papirus-icon-theme

    # System
    brightnessctl
    playerctl
    kdeconnect

    # Files
    thunar
    yazi

    # nvim dependencies
    tree-sitter-cli
    neovim
)

paru -S --needed --noconfirm "${PACKAGES[@]}"
success "Packages installed"

# ── 2. Directories ───────────────────────────────────────
info "Creating config directories..."

mkdir -p "$CONFIG/hypr/conf"
mkdir -p "$CONFIG/hypr/scripts"
mkdir -p "$CONFIG/hypr/noctalia"
mkdir -p "$CONFIG/noctalia"
mkdir -p "$CONFIG/kitty/themes"
mkdir -p "$CONFIG/fastfetch"
mkdir -p "$CONFIG/fish"
mkdir -p "$HOME/Pictures/Wallpapers/ultrawide"
mkdir -p "$HOME/Pictures/Wallpapers/4k"
mkdir -p "$HOME/Pictures/Screenshots"

success "Directories created"

# ── 3. Hyprland ──────────────────────────────────────────
info "Deploying Hyprland config..."

cp "$SCRIPT_DIR/hypr/hyprland.conf"           "$CONFIG/hypr/hyprland.conf"
cp "$SCRIPT_DIR/hypr/hypridle.conf"           "$CONFIG/hypr/hypridle.conf"
cp "$SCRIPT_DIR/hypr/conf/monitors.conf"      "$CONFIG/hypr/conf/monitors.conf"
cp "$SCRIPT_DIR/hypr/conf/keybinds.conf"      "$CONFIG/hypr/conf/keybinds.conf"
cp "$SCRIPT_DIR/hypr/conf/exec.conf"          "$CONFIG/hypr/conf/exec.conf"
cp "$SCRIPT_DIR/hypr/conf/animations.conf"    "$CONFIG/hypr/conf/animations.conf"
cp "$SCRIPT_DIR/hypr/conf/windowrules.conf"   "$CONFIG/hypr/conf/windowrules.conf"
cp "$SCRIPT_DIR/hypr/scripts/gamemode.sh"     "$CONFIG/hypr/scripts/gamemode.sh"
cp "$SCRIPT_DIR/hypr/scripts/keybind-cheatsheet.sh" "$CONFIG/hypr/scripts/keybind-cheatsheet.sh"
chmod +x "$CONFIG/hypr/scripts/"*

success "Hyprland config deployed"

# ── 4. Noctalia ──────────────────────────────────────────
info "Deploying Noctalia config..."

cp "$SCRIPT_DIR/noctalia/settings.json"       "$CONFIG/noctalia/settings.json"

success "Noctalia config deployed"

# ── 5. Kitty ─────────────────────────────────────────────
info "Deploying Kitty config..."

cp "$SCRIPT_DIR/kitty/kitty.conf"             "$CONFIG/kitty/kitty.conf"
# Note: kitty/themes/noctalia.conf is generated by Noctalia/Matugen
# It will be created automatically on first Noctalia launch

success "Kitty config deployed"

# ── 6. Fastfetch ─────────────────────────────────────────
info "Deploying Fastfetch config..."

cp "$SCRIPT_DIR/fastfetch/config.jsonc"       "$CONFIG/fastfetch/config.jsonc"

# Avatar — copy from Pictures if it exists, otherwise warn
if [[ -f "$HOME/Pictures/avatar-nobg.png" ]]; then
    cp "$HOME/Pictures/avatar-nobg.png" "$CONFIG/fastfetch/avatar.png"
    success "Fastfetch avatar copied from ~/Pictures/avatar-nobg.png"
else
    warn "Avatar not found at ~/Pictures/avatar-nobg.png — add your avatar manually to ~/.config/fastfetch/avatar.png"
fi

success "Fastfetch config deployed"

# ── 7. Fish ──────────────────────────────────────────────
info "Deploying Fish config..."

cp "$SCRIPT_DIR/fish/config.fish"             "$CONFIG/fish/config.fish"

success "Fish config deployed"

# ── 8. nvim ──────────────────────────────────────────────
if [[ -d "$SCRIPT_DIR/nvim" ]]; then
    info "Deploying nvim config..."
    mkdir -p "$CONFIG/nvim"
    cp -r "$SCRIPT_DIR/nvim/"*                "$CONFIG/nvim/"
    success "nvim config deployed"
fi

# ── 9. GTK / Qt theming ──────────────────────────────────
info "Applying GTK and font settings..."

gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
gsettings set org.gnome.desktop.interface font-name 'Noto Sans 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'Maple Mono NF 11'
gsettings set org.gnome.desktop.interface document-font-name 'Noto Sans 11'
gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
gsettings set org.gnome.desktop.interface cursor-size 24
# Fix xdg mime defaults
xdg-mime default thunar.desktop inode/directory
xdg-mime default thunar.desktop x-directory/normal

success "GTK and font settings applied"

# ── 10. Wallpaper directories ────────────────────────────
success "Wallpaper directories created at:"
echo "    ~/Pictures/Wallpapers/ultrawide  ← add 5120x1440 wallpapers here"
echo "    ~/Pictures/Wallpapers/4k         ← add 3840x2160 wallpapers here"

# ── Done ─────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Rocko_DE_Final deployed!         ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo "  Next steps:"
echo "  1. Add wallpapers to ~/Pictures/Wallpapers/ultrawide/ and ~/Pictures/Wallpapers/4k/"
echo "  2. Add avatar image to ~/Pictures/avatar-nobg.png (if not present)"
echo "  3. Run qt6ct and select 'noctalia' color scheme"
echo "  4. Log out and back in (or reboot)"
echo "  5. On first launch — Noctalia Settings → Color Scheme → Templates"
echo "     Enable: GTK, Qt, Hyprland, Kitty"
echo ""
echo "  Key bindings:"
echo "  Super+D          — App launcher"
echo "  Super+\`          — Drop-down terminal"
echo "  Super+F1         — Drop-down file manager"
echo "  Super+slash      — Keybind cheatsheet"
echo "  Super+Shift+W    — Random wallpaper"
echo "  Super+M          — Control center"
echo "  Super+X          — Session menu"
echo ""
